# Generated by Django 4.2.27 on 2025-12-30 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('beds', models.IntegerField()),
                ('baths', models.FloatField()),
                ('image_url', models.URLField()),
            ],
        ),
    ]
