# Generated by Django 4.2.27 on 2025-12-30 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='image_url',
        ),
        migrations.AddField(
            model_name='house',
            name='address',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='house',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='house',
            name='image_urls',
            field=models.JSONField(default=[]),
            preserve_default=False,
        ),
    ]
