# Generated by Django 4.2.27 on 2025-12-31 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("houses", "0003_rename_address_house_address_line_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="HouseDislike",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("house", models.ForeignKey(on_delete=models.deletion.CASCADE, related_name="dislikes", to="houses.house")),
            ],
        ),
    ]
