# Generated by Django 4.2.27 on 2025-12-31 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("houses", "0004_houselike"),
        ("houses", "0004_housedislike"),
    ]

    operations = []
