# Generated by Django 4.2.27 on 2025-12-31 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("houses", "0005_merge_0004_houselike_0004_housedislike"),
    ]

    operations = [
        migrations.CreateModel(
            name="HouseSave",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("house", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="saves", to="houses.house")),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(fields=("house",), name="unique_house_save"),
                ],
            },
        ),
    ]
